site_name: Вики
site_url: https://wiki.staki.online
theme:
  name: material
  language: ru
  logo: assets/minecraft_title.png
  palette:
    primary: green
  font:
    text: Roboto
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    #    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.tracking
plugins:
  - search:
      lang:
        - ru
        - en
markdown_extensions:
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  analytics: custom
extra_css:
  - stylesheets/extra.css

nav:
  - База:
      - index.md
      - О сервере:
          - base/motivation.md
          - base/philosophy.md
          - base/principles.md
      - Правила:
          - Основные: base/rules/main.md
          - Коммуникация: base/rules/communication.md
          - Моды: base/rules/mods.md
      - Часто задаваемые вопросы: base/faq.md
      - base/decisions.md
      - base/donate.md
  - Начать:
      - Аккаунт:
          - start/register.md
          - start/skin.md
      - Игра:
          - start/specifications.md
          - start/install.md
          - start/first-start.md
          - start/optimization.md
      - Помощь:
          - Лаги: start/help/lags.md
          - Баги: start/help/bugs.md
          - Удаление: start/help/reinstall.md
  - Геймплей:
      - game/client.md
      - Моды:
          - JEI: game/mods/main/jei.md
          - Voice Chat: game/mods/main/voice-chat.md
          - Create:
              - Create: game/mods/main/create/index.md
              - Crafts And Additions: game/mods/main/create/crafts-and-additions.md
              - Copycats+: game/mods/main/create/copycats-plus.md
              - Connected: game/mods/main/create/connected.md
              - Diesel Generators: game/mods/main/create/diesel-generators.md
              - Enchantment Industry: game/mods/main/create/enchantment-industry.md
              - Escalated: game/mods/main/create/escalated.md
              - Farmer's Delight: game/mods/main/create/farmers-delight.md
              - Mob Spawners: game/mods/main/create/mob-spawners.md
              - Numismatics: game/mods/main/create/numismatics.md
              - Ore Excavation: game/mods/main/create/ore-excavation.md
              - Pattern Schematics: game/mods/main/create/pattern-schematics.md
              - Power Loader: game/mods/main/create/power-loader.md
              - Steam 'n' Rails: game/mods/main/create/steam-n-rails.md
              - Декорации: game/mods/main/create/decorations.md
          - Epic Fight: game/mods/main/epic-fight.md
          - game/mods/main/armor.md
          - TaCZ: game/mods/main/tacz.md
          - Farmer's Delight: game/mods/main/farmers-delight.md
          - Декорации: game/mods/main/furniture.md
          - game/mods/main/animals.md
          - ComputerCraft: game/mods/main/computercraft.md
          - SecurityCraft: game/mods/main/securitycraft.md
          - Let's Do:
              - Vinery: game/mods/main/lets-do/vinery.md
              - Brewery: game/mods/main/lets-do/brewery.md
              - Beachparty: game/mods/main/lets-do/beachparty.md
          - game/mods/main/supplementaries.md
          - game/mods/main/waterframes.md
          - game/mods/main/exposure.md
          - game/mods/main/zetter.md
      - Вспомогательное:
          - game/mods/secondary/secondary-mods.md
          - game/mods/secondary/optional.md
      - Другое:
          - game/util/grieflogger.md
  - Полезности:
      - Карта: utility/map.md